name: Pull Request Triage

permissions:
  pull-requests: write
  issues: write

on: [pull_request_target]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@9fcb2c2f5584144ca754f8bfe8c6f81e77753375
        with:
          configuration-path: .github/labeler.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: CodelyTV/pr-size-labeler@54ef36785e9f4cb5ecf1949cfc9b00dbb621d761
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/xs'
          xs_max_size: '10'
          s_label: 'size/s'
          s_max_size: '50'
          m_label: 'size/m'
          m_max_size: '200'
          l_label: 'size/l'
          l_max_size: '400'
          xl_label: 'size/xl'
          fail_if_xl: 'false'
          message_if_xl: >
            This PR exceeds the recommended size of 400 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
